#!/usr/bin/env php
<?php

require __DIR__ . '/../../vendor/autoload.php';

$app = new Firestark\App;
$app->instance('app', $app);
$app->instance('statuses', new Firestark\Statuses);

Facade::setFacadeApplication($app);


including(__DIR__ . '/../../bindings');
including(__DIR__ . '/bindings');
including(__DIR__ . '/statuses');
including(__DIR__ . '/../../app/procedures');


$shell = new \Psy\Shell;
$shell->run();